"""Where uploaded PDF files live on disk (a Docker volume in production)."""

import logging
import uuid
from pathlib import Path

from app.core.config import settings

logger = logging.getLogger(__name__)


def ensure_upload_dir() -> None:
    settings.upload_dir.mkdir(parents=True, exist_ok=True)


def path_for(stored_filename: str) -> Path:
    # stored_filename is always generated by save_pdf, never taken from the user,
    # so it can't contain "../" tricks. .name is an extra safety net.
    return settings.upload_dir / Path(stored_filename).name


def save_pdf(data: bytes) -> str:
    """Write the bytes under a new random name and return that name."""
    ensure_upload_dir()
    stored_filename = f"{uuid.uuid4().hex}.pdf"
    with open(path_for(stored_filename), "xb") as file:  # "x": never overwrite
        file.write(data)
    return stored_filename


def delete_pdf(stored_filename: str) -> None:
    try:
        path_for(stored_filename).unlink(missing_ok=True)
    except OSError:
        logger.exception("Could not delete file %s", stored_filename)
